######################################################################
# Automatically generated by qmake (3.1) Thu Apr 19 07:07:29 2018
######################################################################

TEMPLATE = app
TARGET = rarchive
INCLUDEPATH += . ../../ ../../include
LIBS += -larchive
QT += core concurrent
DEFINES += QT_DEPRECATED_WARNINGS

# Input
HEADERS += ../../include/QArchive.hpp
SOURCES += main.cc ../../src/QArchive.cc
