#ifndef QARCHIVE_GLOBAL_HPP_INCLUDED
#define QARCHIVE_GLOBAL_HPP_INCLUDED
#include <QtCore/QtGlobal>

// Generated by CMake or QMake.
#include "config.h"

#ifdef QARCHIVE_STATIC
# define QARCHIVE_EXPORT
#else

# ifdef QARCHIVE_BUILD
#  define QARCHIVE_EXPORT Q_DECL_EXPORT
# else
#  define QARCHIVE_EXPORT Q_DECL_IMPORT
# endif // QARCHIVE_BUILD
#endif // QARCHIVE_STATIC

#endif // QARCHIVE_GLOBAL_HPP_INCLUDED
